# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27-zodb4
        - python: 2.7
          env: TOXENV=py27-zodb5
        - python: 3.5
          env: TOXENV=py35-zodb4
        - python: 3.5
          env: TOXENV=py35-zodb5
        - python: 3.6
          env: TOXENV=py36-zodb4
        - python: 3.6
          env: TOXENV=py36-zodb5
        - python: pypy
          env: TOXENV=pypy-zodb4
        - python: pypy
          env: TOXENV=pypy-zodb5
        - python: pypy3
          env: TOXENV=pypy3-zodb4
        - python: pypy3
          env: TOXENV=pypy3-zodb5
        - python: 3.7
          env: TOXENV=py37-zodb5
          dist: xenial
          sudo: true
        - python: 3.8
          env: TOXENV=py38-zodb5
          dist: xenial
          sudo: true

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - repoze-checkins@lists.repoze.org
