---
name: tests
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.13'
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
          - 'pypy-3.10'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip|${{ hashFiles('setup.py') }}|${{ hashFiles('tox.ini') }}
      - run: pip install tox
      - run: tox -e py
